### PR TITLE
Support jsx file extension

### PR DESCRIPTION
**Pull request by js62789**

### CODE REVIEW

**Comment by js62789** [comment]
Wait, this is insufficient, I need to make one more update.

**Comment by js62789** [comment]
Ok this is ready to go. Note that the regex includes a question mark so that both `.js` and `.jsx` are supported. Until this is published, we're manually overriding our web pack config [here](https://github.com/gas-buddy/consumer-web/pull/1018/files#diff-a58d55bdb5770c78ad512f8e91f8d051R17).

**Comment by js62789** [comment]
Bueller?

**Comment by djMax** [comment]
Why are we considering this?

**Comment by dhruv-m-patel** [comment]
@djMax we started separating the components that render jsx vs the ones that connect data to those components. In other words, an `index.js` would use `connect` to bind data/dispatchers to components using `mapStateToProps` and `mapDispatchToProps` whereas the components would be using `.jsx` extension and would contain jsx (with some other code to perform effects / callbacks etc.)

We had introduced compatible configs in identity-web and payment-web but having those changes in this would simplify it without us having to replicate at other places.

**Comment by djMax** [comment]
I dislike using file extensions to signal subtle things like this.

**Comment by djMax** [comment]
This would imply to me that js files can never have "jsx" in them, and that just isn't true across the codebase nor do I think it should be.

**Comment by dhruv-m-patel** [comment]
This PR just adds support for having jsx files; current js files would continue to be able to work with jsx.

**Comment by jasisk** [comment]
I agree. If you want a convention, you’re better off at the folder structure level. File name if you have to. Extension is a bit heavy since it’s hard coded in module resolving—makes moving code between toolchains more of a task.

**Comment by dhruv-m-patel** [comment]
I would agree with that but currently we have to add jsx support manually in react projects, which we wouldn't have to with this change. To clarify, this PR only adds support for `jsx` files and does not enforce a standard of separation.

**Comment by djMax** [comment]
The guidance seems to be "don't use JSX"

**Pull request closed without merging**
