### PR TITLE
Minimize CSS assets

### PR DESCRIPTION
**Pull request by js62789**
Want to hear a bad joke? We're not minimizing CSS assets.

### CODE REVIEW

**Comment by wallycarvalho** [comment]
numbers please? 😆

**Comment by js62789** [comment]
**consumer-web Comparison**
Before: 191k
After: 120k

**Review by wallycarvalho — APPROVED** [review]

**Review by ty-grubber — APPROVED** [review]

**Comment by js62789** [comment]
@djMax @jasisk Are there any steps you'd like to take before we can merge this?

**Comment by jasisk** [comment]
Any idea how this might be impacting JS assets (size-wise), if at all?

**Comment by js62789** [comment]
**consumer-web Comparison**
Before
client.js 915k
vendor.js 147k

After
client.js 910k
vendor.js 146k

Net loss of 6k... It looks like I need to look into why our client build is so big, but we should treat that as a different issue since this branch effectively decreases bundle size.

**Comment by jasisk** [comment]
Sounds good. I’ll confirm it’s an even-ish swap for the default js minifier but I won’t hold you up for that. I’m cool if @djmax has no concerns.

**Comment by js62789** [comment]
@djMax ping

**Pull request merged**
